# See LICENSE file for full copyright and licensing details.

{
    'name': 'School',
    'version': '11.0.1.0.0',
    'author': 'Serpent Consulting Services Pvt. Ltd.',
    'website': 'http://www.serpentcs.com',
    'category': 'School Management',
    'license': "AGPL-3",
    'complexity': 'easy',
    'Summary': 'A Module For School Management',
    'images': ['static/description/EMS.jpg'],
    'depends': ['hr', 'crm', 'account', 'account_check_printing', 'account_cancel'],
    'data': ['security/school_security.xml',
             'security/ir.model.access.csv',
             'security2/ir.model.access.csv',
             'wizard/terminate_reason_view.xml',
             'wizard/wiz_send_email_view.xml',
             'views/student_view.xml',
             'views/school_view.xml',
             'views/teacher_view.xml',
             'views/parent_view.xml',
             'data/student_sequence.xml',
             'views/account_payment_group_invoice_wizard_view.xml',
             'views/account_payment_group_view.xml',
             'wizard/assign_roll_no_wizard.xml',
             'wizard/move_standards_view.xml',
             'views/report_view.xml',
             'views/identity_card.xml',
             'views/template_view.xml',
             'views/account_invoice_view.xml',

             'fees_views/school_fees_view.xml',
             'fees_views/school_fees_sequence.xml',
             'fees_views/student_payslip.xml',
             'fees_views/student_fees_register.xml',
             'fees_views/report_view.xml',
             'fees_views/subscription_scheduler.xml',
             'fees_views/subscription_email_template.xml',
             'fees_views/discount_view.xml',

             'extra_tab_view/academic_performance.xml',
             'extra_tab_view/attendance.xml',
             'extra_tab_view/branch.xml',
             'extra_tab_view/classification.xml',
             'extra_tab_view/education_level.xml',
             'extra_tab_view/notification.xml',
             'extra_tab_view/offence.xml',
             'extra_tab_view/relationship.xml',
             'extra_tab_view/school_region.xml',
             'extra_tab_view/sms_tab.xml',
             'extra_tab_view/student_type.xml',
             'extra_tab_view/study_history.xml',

             ],
    'demo': ['demo/school_demo.xml',
             'demo/school_fees_demo.xml'],
    'installable': True,
    'application': True
}
